### ISSUE TITLE
Disk usage (data on disk) increases indefinitely during use with purge off

### ISSUE THREAD

**Issue by Lennart00** [fiddyschmitt/TCP-over-File#8]
Hello Fidel,

I have run into an Issue with Version 1.05

I have the file tunnel using my ramdisk, which is limited to a maximum of 1 or 2 GB currently in my configuration with a NTFS filesystem.

During longer session of transferring files and generally just working with this setup i ran into the following situation:

The filetunnel application was reporting no available disk space left at some point.
The partition in windows under local computer was showing to be completely 100% full.
The files themselves were displayed to be small on the view presented by explorer, but when clicking on the properties of the directory, it displayed a disk usage of the full gigabyte.
I will send some pictures later on. It was kind of late when i ran into this and just restarted everything to continue.

Best regards
Lennart

**Comment by Lennart00** [comment]
With purging disabled at least this is what it looks like after downloading 1.2 gigabytes of data.

![image](https://github.com/fiddyschmitt/TCP-over-File/assets/73488709/938d819f-084d-454b-a633-7f259a2c72e9)

I will repeat the same operation with purging on.

**Comment by Lennart00** [comment]
This was a mistake on my part.
I was running a mismatch between purging on and purging off between both machines.
With purging on both machines, the disk usage problem does not appear/happen.

**Comment by Lennart00** [comment]
Hi Fidel,
thank you for this technical explanation.
Im closing this issue.
Best regards
Lennart

**Comment by fiddyschmitt** [comment]
> Explorer doesn't always show an accurate file size (as shown in your screenshot), because the file is "in use".

There is an explanation of this behaviour here:

https://devblogs.microsoft.com/oldnewthing/20111226-00/?p=8813
